### ISSUE TITLE
BmcDataStore -> rename is not thread safe. throwing java.io.IOException: Unable to perform rename

### ISSUE THREAD

**Issue by piyushg** [oracle/oci-hdfs-connector#18]
https://github.com/oracle/oci-hdfs-connector/blob/master/hdfs-connector/src/main/java/com/oracle/bmc/hdfs/store/BmcDataStore.java

BmcDataStore -> rename is not thread safe and throwing IOException.  when using spark to store dataset to object storage using this connector we are hitting across this issue.  data access to object storage through connector should be thread safe.

Stacktrace:
[Stacktrace_2.txt](https://github.com/oracle/oci-hdfs-connector/files/3468585/Stacktrace_2.txt)

Code reference from where exception is getting thrown: 

private void rename(final String sourceObject, final String destinationObject)
                  throws IOException {
              LOG.debug("Attempting to rename {} to {}", sourceObject, destinationObject);
              try {
                  final String newEntityTag =
                          new RenameOperation(
                                          this.objectStorage,
                                          this.requestBuilder.renameObject(
                                                  sourceObject, destinationObject))
                                  .call();
                  this.statistics.incrementWriteOps(1); // 1 put
                  LOG.debug("Newly renamed object has eTag {}", newEntityTag);
              } catch (final Exception e) {
                  LOG.debug("Failed to rename {} to {}", sourceObject, destinationObject, e);
                  throw new IOException("Unable to perform rename", e);   <-------- ERROR line ------>
              }
          }

**Comment by andy-miles** [comment]
Thanks for reporting this issue.  We'll look into reproducing this issue and addressing it.

**Comment by sumitkdey** [comment]
Per the attached callstack, the rename operation failed due to the service returning the below failure.
`Caused by: com.oracle.bmc.model.BmcException: (404, ObjectNotFound, false) null (opc-request-id: fbe278d7-f0ae-48b5-bf3f-fb819cddc8c3)`
The object that was attempted to be renamed was no longer present. The connector does not attempt to detect, prevent or serialize access to one object from multiple threads. It is the responsibility of the caller to ignore expected failures (ex rename failure if the same object was deleted by a separate thread).
