### ISSUE TITLE
Support for Apache Flink

### ISSUE THREAD

**Issue by rohitagl91** [oracle/oci-hdfs-connector#27]
Wanted to know if there is a similar library for integrating Apache flink with OCI Object Storage?

**Comment by tsammut** [comment]
Hi @rohitagl91.

There is not, sorry. I am not familiar with Flink, but it appears it supports S3. 

https://ci.apache.org/projects/flink/flink-docs-stable/ops/filesystems/s3.html

It is likely, this will work with OCI's Amazon S3 Compatible API.

https://docs.cloud.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm

Make sure Flink is configured for path-style access. Also, since, at least by looking at the Flink docs, Flink does not support specifying a "region name" like us-phoenix-1, Flink+S3 will only work your OCI tenancy's home region.

hope this helps!

**Comment by mricken** [comment]
Thanks for your help, @tsammut . @rohitagl91 , since this is not directly related to the HDFS connector, I will close this issue. Please feel free to re-open to discuss the HDFS connector.
